apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/grvsobha/argcod.git
    targetRevision: main
    path: argocd-test
  destination: 
    server: https://kubernetes.default.svc
    namespace: frontend

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  clusterResourceNamespace: argocd
  syncOptions:
    - CreateNamespace=true
    - SecretName=dockerhub-credentials
  automated:
      selfHeal: true
      prune: true
      
